name: Rust Builder

on:
  schedule:
    # Triggers the workflow every day at 5:30 UTC:
    - cron:  '30 5 * * *'
  push:
    branches:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  registry: ghcr.io
  AWS_SHARED_CREDENTIALS_FILE: "${{ github.workspace }}/.aws/credentials"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        toolchain_version:
          - stable
          - nightly
        rust_version:
          - { major: 1, minor: 65, patch: 0 }
        debian_suite:
          - bullseye
        # Do *not* execute scheduled runs for matrix.toolchain_version == 'stable'
        scheduled:
          - ${{ github.event_name == 'schedule' }}
        exclude:
          - scheduled: true
            toolchain_version: stable

    name: Build and push rust_builder:${{ matrix.rust_version.major }}.${{ matrix.rust_version.minor }}.${{ matrix.rust_version.patch }}-${{ matrix.debian_suite }}-${{ matrix.toolchain_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials for cicd-devnet-1 account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::367397670706:role/GitHubRole
          role-session-name: GitHubRole-session
          aws-region: us-east-1
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Add profile credentials to .aws/credentials
        run: |
            aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile default
            aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile default
            aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile default

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.registry }}/${{ github.repository_owner }}/rust_builder
          tags: |
            type=raw,value=${{ matrix.toolchain_version }}-latest
            type=raw,value=${{ matrix.rust_version.major }}.${{ matrix.rust_version.minor }}.${{ matrix.rust_version.patch }}-${{ matrix.debian_suite }}-${{ matrix.toolchain_version }}
            type=raw,value=${{ matrix.rust_version.major }}.${{ matrix.rust_version.minor }}-${{ matrix.debian_suite }}-${{ matrix.toolchain_version }}
            type=schedule,pattern=${{ matrix.rust_version.major }}.${{ matrix.rust_version.minor }}.${{ matrix.rust_version.patch }}-${{ matrix.debian_suite }}-${{ matrix.toolchain_version }}-{{date 'YYYYMMDD'}}
            type=schedule,pattern=${{ matrix.rust_version.major }}.${{ matrix.rust_version.minor }}-${{ matrix.debian_suite }}-${{ matrix.toolchain_version }}-{{date 'YYYYMMDD'}}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          secret-files: |
            "aws=${{ github.workspace }}/.aws/credentials"
          build-args: |
            TOOLCHAIN_VERSION=${{ matrix.toolchain_version }}
            RUST_VERSION=${{ matrix.rust_version.major }}.${{ matrix.rust_version.minor }}.${{ matrix.rust_version.patch }}
            DEBIAN_SUITE=${{ matrix.debian_suite }}
          context: ./rust_builder/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.registry }}/${{ github.repository_owner }}/rust_builder:${{ matrix.toolchain_version }}-latest
